### ISSUE TITLE
Showing KVNProgress on table view fails

### ISSUE THREAD

**Issue by Frohmen** [AssistoLab/KVNProgress#45]
I'm trying to show KVNProgress on a table view, but have run into some trouble. Check out the picture below to see how it looks like.

![kvnprogress](https://cloud.githubusercontent.com/assets/2903455/8007117/fe6fdb5c-0b99-11e5-8448-3daa923dfb8d.jpg)

**Comment by kevin-hirsch** [comment]
Hello @Frohmen, it should now be fixed. #80 
Sorry for the late answer.

It will be available in 2.4, until then, you can use the latest version of KVNProgress with this:
```ruby
pod 'KVNProgress', :git => 'https://github.com/AssistoLab/KVNProgress.git', :commit => '302514b'
```
