### ISSUE TITLE
KVNProgress bug with swift. 

### ISSUE THREAD

**Issue by nuttikung** [AssistoLab/KVNProgress#48]
I have the problem with KVNProgress.

- showProgress(0, "Downloading...")  Show Correct
- updateProgress(Some CGFLoat value, animate:trre )  >> It's a problem

Not sure it's delay? because I watched it's moving to 1.0 have a few delay but for 0.1 0.2 etc. Nothing moves.

**Comment by kevin-hirsch** [comment]
Hello @nuttikung,

Can you tell me where are you calling those methods?

**Comment by nuttikung** [comment]
<img width="949" alt="screen shot 2015-07-15 at 9 42 51 am" src="https://cloud.githubusercontent.com/assets/8456620/8689740/f796a422-2ad5-11e5-929f-fcb91d6c0686.png">

Here is my code. I put it for update percent when user download file. but it's not update progress anytime.

**Comment by kevin-hirsch** [comment]
You have to call first `showProgress` and then update it via `updateProgress`. I do not see any `showProgress` in your screenshot. Could that be your issue?

**Comment by nuttikung** [comment]
No,I already have it. Now I know what's bug for me I think my variable (percentage is more 1 decimal?) It's can't update.  Now I fixed it. 

Thank you so much.

**Comment by kevin-hirsch** [comment]
Hello @nuttikung,

The percentage is a number between **0** and **1**.
How did you fix your problem?
