### ISSUE TITLE
After POD update Xcode is failing due to KNProgress error

### ISSUE THREAD

**Issue by sdalai** [AssistoLab/KVNProgress#56]
Here is error code

ld: library not found for -lPods-KVNProgress
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kevin-hirsch** [comment]
Hello @sdalai, did you did well a `pod install` from the command line? If yes, I found this [thread](http://stackoverflow.com/questions/24078597/cocoapods-ld-library-not-found-for-lpods-projectname) on stackoverflow. Take a look at the accepted answer, hope it helps!
Keep me posted!
