### ISSUE TITLE
Showing loader above keyboard?

### ISSUE THREAD

**Issue by freak4pc** [AssistoLab/KVNProgress#70]
Is it a possibility to present the loader over the keyboard? Currently displaying the loader while a text field is the first responder, leaves the keyboard visible (and active) which lets the user act on it. 

From what I know it should be possible to create a new UIWindow with a Status Bar Level so the progress view could overlay the keyboard as well.

What are your thoughts on this? 

Thank you :)

**Comment by Jackson0111** [comment]
Having the same issue. Solutions?

**Comment by kevin-hirsch** [comment]
I will take a look at a solution. In the meantime, a workaround could simply be resigning the first responder to hide the keyboard before showing the loader.

**Comment by freak4pc** [comment]
@kevin-hirsch That's what we're currently doing. 
But generally speaking, the solution I suggested with a UIStatusBarLevel UIWindow should work well, I've done that for a similar component.

**Comment by kevin-hirsch** [comment]
Alright! Thanks for the tip, I will take a look a that `UIStatusBarLevel UIWindow` thing 👍

**Comment by erdem-inan** [comment]
Hey guys,
This have been done in this commit: a741fea488a5c5a3500996b9500bc4f0645930b8
I leave the task open, waiting for your feedback :) .

**Comment by kevin-hirsch** [comment]
@freak4pc Can you tell us if it is resolved now?

**Comment by freak4pc** [comment]
@kevin-hirsch do you mean using that specific commit ? 
I haven't seen a version update on KVNProgress (still at 2.2.4).

**Comment by freak4pc** [comment]
Hey guys, I can confirm https://github.com/AssistoLab/KVNProgress/commit/a741fea488a5c5a3500996b9500bc4f0645930b8 resolved this issue :) 

Let's get this merged !

**Comment by kevin-hirsch** [comment]
Done and available from CocoaPods v2.3 😉

**Comment by freak4pc** [comment]
Confirmed - Update to v2.3 fixes issue. 
Thanks to all involved !
