### ISSUE TITLE
UIView

### ISSUE THREAD

**Issue by pjebs** [AssistoLab/KVNProgress#71]
What would I need to do to use the standard spinner UIVIew as a element to put in my UI.

What I am saying is using it as a normal control without the status bar, popup etc.

**Comment by kevin-hirsch** [comment]
Hello @pjebs!
What you want is use the circle part only ? I mean the content (loader + text) inside the popup?

**Comment by pjebs** [comment]
At the time, I noticed that the spinning circle part could not be used by itself. I wanted to use it without the rest of the control. It would require a refactoring of the code to make it more modular but probably isn't worth the time for either of us.

I'll close the issue because it was from a long time ago for a project that is now finished.

**Comment by kevin-hirsch** [comment]
Alright! Anyway, it would be simpler to code this directly than to use the KVNProgress to suits your needs. Something like http://stackoverflow.com/a/26578895/2571566
