### ISSUE TITLE
crashed while updateStatus:

### ISSUE THREAD

**Issue by uxight** [AssistoLab/KVNProgress#73]
Crashed: NSOperationQueue 0x1775a150 :: NSOperation 0x1785afc0 (QOS: LEGACY)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000090000010

KVNProgress.m line 1008
-[KVNProgress updateStatus:]

I don't know exactly where and why it happens, but Fabric Crashlytics Tool send me crash report quite 	
frequently. My code call updateStatus: from in 2(or more) progress blocks but not in the thread. Why it happens?

(p.s. sorry for my english)

**Comment by kevin-hirsch** [comment]
Hello @uxight 
Can you reproduce this crash every time? On which thread do you call the `updateStatus: ` method?
Try on the main thread, your issue could come from there ;)
To call it on the main thread, do:

```objc
dispatch_async(dispatch_get_main_queue(), ^{
   [KVNProgress updateStatus:@"yourNewStatus"];
});
```
