### ISSUE TITLE
Can you show me swift code for adding full screen View 

### ISSUE THREAD

**Issue by sreeji44** [AssistoLab/KVNProgress#77]
can you add swift code for adding Fullscreen view

**Comment by kevin-hirsch** [comment]
Doesn't this work already doing this?

```swift
let conf = KVNProgressConfiguration.defaultConfiguration()
conf.fullScreen = true
KVNProgress.setConfiguration(conf)
KVNProgress.showSuccessWithStatus("Success !")
```

**Comment by sreeji44** [comment]
@kevin-hirsch 

func config(_: KVNProgressConfiguration){
        var Basic = KVNProgressConfiguration()
        Basic.statusColor = UIColor.whiteColor()
        Basic.circleStrokeForegroundColor = UIColor.whiteColor()
        Basic.circleStrokeBackgroundColor = UIColor(white: 1.0, alpha: 0.3)
        Basic.circleFillBackgroundColor = UIColor(white: 1.0, alpha: 0.1)
        Basic.circleSize = 110.0
        Basic.lineWidth = 1.0
        Basic.fullScreen = true
        Basic.showStop = true
        Basic.stopRelativeHeight = 0.4
        Basic.allowUserInteraction = true
        Basic.backgroundFillColor = UIColor(red: 0.173, green: 0.263, blue: 0.856, alpha: 0.9)
        Basic.backgroundTintColor = UIColor(red: 0.173, green: 0.263, blue: 0.856, alpha: 0.4)
        
        
    
            
        }
actually i tried all way....

**Comment by kevin-hirsch** [comment]
And that doesn't work?

**Comment by kevin-hirsch** [comment]
Do you assign this config to the `KVNProgress` like so?

```swift
KVNProgress.setConfiguration(Basic)
```

**Comment by sreeji44** [comment]
@kevin-hirsch  where i want to set this code ?. ok let me try... actually i added lot of codes right..

**Comment by kevin-hirsch** [comment]
Try with this:

```swift
func setupConfig() {
    var Basic = KVNProgressConfiguration()
    Basic.statusColor = UIColor.whiteColor()
    Basic.circleStrokeForegroundColor = UIColor.whiteColor()
    Basic.circleStrokeBackgroundColor = UIColor(white: 1.0, alpha: 0.3)
    Basic.circleFillBackgroundColor = UIColor(white: 1.0, alpha: 0.1)
    Basic.circleSize = 110.0
    Basic.lineWidth = 1.0
    Basic.fullScreen = true
    Basic.showStop = true
    Basic.stopRelativeHeight = 0.4
    Basic.allowUserInteraction = true
    Basic.backgroundFillColor = UIColor(red: 0.173, green: 0.263, blue: 0.856, alpha: 0.9)
    Basic.backgroundTintColor = UIColor(red: 0.173, green: 0.263, blue: 0.856, alpha: 0.4)

    // ⚠️ This line is very important!
    KVNProgress.setConfiguration(Basic)
}

// You setup the KVNProgress configuration
setupConfig()

// Then you use it
KVNProgress.showProgress(0.0, status: "Loading...")

ViewController.dispatch_main_after(5.5, block: {() -> Void in
    KVNProgress.dismiss()    
})
```

**Comment by sreeji44** [comment]
@kevin-hirsch  thank you very much you are awesome 👍  💯

**Comment by kevin-hirsch** [comment]
Great! :)
