### ISSUE TITLE
SIGABRT

### ISSUE THREAD

**Issue by Frohmen** [AssistoLab/KVNProgress#78]
After upgrading to the latest version 2.2.4 i get a `SIGABRT` inside the `sharedView` function when calling `KVNProgress.showWithStatus`

**Comment by kevin-hirsch** [comment]
Hello @Frohmen! Try using the latest version of KVNProgress (2.3) available via CocoaPods.
Give me your feedback 🙃

**Comment by Frohmen** [comment]
I'm afraid it still doesn't work, getting the same error as before

**Comment by kevin-hirsch** [comment]
Can you reproduce the issue every time?
Also, can you show me the logs of the crash, please?

**Comment by Frohmen** [comment]
Yes it happens every time
Sorry for not understanding, but what do you mean with the logs of the crash?

**Comment by Frohmen** [comment]
I just found this in the debug console:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/97259200-1DAB-4656-9535-E0E29DB93D2A/Dagens Kungsbacka.app/Frameworks/KVNProgress.framework> (loaded)' with name 'KVNProgressView''

**Comment by Frohmen** [comment]
It might have something to do with that I'm using Swift and using the pod as framework

**Comment by kevin-hirsch** [comment]
Closed through #75 (answer [here](https://github.com/AssistoLab/KVNProgress/issues/75#issuecomment-240962783))
