### ISSUE TITLE
even import only (from pods) crashes OpenGL view

### ISSUE THREAD

**Issue by mattem86** [AssistoLab/KVNProgress#88]
I have a OpenGL ES 2.0 view, which I wanted to overlay with the KVNProgress. Every single time, I opened the GLView **twice**, the app crashes with _gpus_ReturnGuiltyForHardwareRestart_ ... Even if only imported the KVNProgress module via CocoaPods and no showing of the KVNProgress itself...

**Comment by kevin-hirsch** [comment]
Hello @mattem86, thanks for using this library!

Are you sure this crash is from KVNProgress itself? Do the crash disappear when you remove the `KVNProgress` import?

**Comment by mattem86** [comment]
Yep, the crash disappears, if I do not import KVNProgress within the ViewController which contains the GLView. I didn't believe that to, so I double-checked :) But I will try it once again tomorrow...

**Comment by kevin-hirsch** [comment]
So the `view` of your view controller is a `GLView`?

**Comment by mattem86** [comment]
Not exactly, the View in my View Controller has a View, which is holds an GLKView inside and is a GLKViewDelegate


Am 12. September 2016 um 16:30:49, Kevin Hirsch (notifications@github.com) schrieb:

So the view of your view controller is a GLView?

**Comment by kevin-hirsch** [comment]
So if you remove the "import KVNProgress" statement, the app does not crash anymore?
Which version of CocoaPods are you using? (`pod --version`)

**Comment by mattem86** [comment]
Sorry, I was busy the last week ... I use pod 1.0.0 ... but, something changed in the meantime, the app crashes no more when I import KVNProgress on that particular ViewController... maybe some other pod were interfering? I have to try again...!


Am 13. September 2016 um 16:22:19, Kevin Hirsch (notifications@github.com) schrieb:

So if you remove the "import KVNProgress" statement, the app does not crash anymore?
Which version of CocoaPods are you using? (pod --version)

**Comment by mattem86** [comment]
Ha! It is the Viewcontroller which I segue off from to reach the new Viewcontroller with the GLView. So, if I import (just import!) KVNProgress in my ViewController A and I segue off to my ViewController B (which contains my GLView), then the crash appears at the second time I segue. Weird.


Am 20. September 2016 um 11:37:08, Matthias Temmen (matthias.temmen@icloud.com) schrieb:

Sorry, I was busy the last week ... I use pod 1.0.0 ... but, something changed in the meantime, the app crashes no more when I import KVNProgress on that particular ViewController... maybe some other pod were interfering? I have to try again...!


Am 13. September 2016 um 16:22:19, Kevin Hirsch (notifications@github.com) schrieb:

So if you remove the "import KVNProgress" statement, the app does not crash anymore?
Which version of CocoaPods are you using? (pod --version)

**Comment by mattem86** [comment]
Ok, seems to be a bug in the GLView Framework I was using ... I was trying again yesterday and everything went well, after updating the specific framework!
